name: Precheck Build

on:
  pull_request:
    branches:
      - master

jobs:
  precheck:
    name: Precheck Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
